### ISSUE TITLE
你好  一键部署到Vercel，报这个错咋回事

### ISSUE THREAD

**Issue by Joe12-24** [weekend-project-space/e9x-fun#2]
An unexpected error has occurred. Our team has been notified and will resolve this error as soon as possible.

Developer details
TypeError: r.at is not a function
    at eO (https://vercel.com/_next/static/chunks/pages/%5BteamSlug%5D/%5Bproject%5D/%5Bid%5D-f9c4f5c44a05a3fb.js:30:9263)
    at https://vercel.com/_next/static/chunks/pages/%5BteamSlug%5D/%5Bproject%5D/%5Bid%5D-f9c4f5c44a05a3fb.js:30:25585
    at rs (https://vercel.com/_next/static/chunks/main-926e2356b1f749b1.js:9:38885)
    at ag (https://vercel.com/_next/static/chunks/main-926e2356b1f749b1.js:9:54220)

**Comment by weekend-project-space** [comment]
已解决
